siefkenj/IBLLinearAlgebra

- problemsets-mat223/linearalbegra.tex
Just trying this pull request thing out for the first time.
> First pull request.

- problemsets-mat223/linearalbegra.tex
Pretty simple, not much to say here I think.
> Finished problem 23.

- problemsets-mat223/linearalbegra.tex
Just added one more solution, finishing problem 21, to test this new branch thing. 
Ended up being *slightly* more complicated. When I first tried to push the branch I made locally, it complained that there was no upstream branch, so I googled a bit and found out I had to do this: 
`git push --set-upstream origin prob21`
Then everything worked though. I'm not 100% sure why I had to do that, but it *seems* to have worked.
If/when you approve that one solution I added, we'll see how this branch merging/syncing thing goes, and I can start working on the next problems much more smoothly.
> Finished problem 21, and testing new branch workflow.

- problemsets-mat223/linearalbegra.tex
Done one more, just three parts. I'll stop here for the night, until I know for sure that doing all of these branches off of the master won't later conflict with each other in some  way that I don't understand yet.
> Finished problem 22.

- problemsets-mat223/linearalbegra.tex
It's hard to avoid the conflation of vectors and points here, so let me know how you think I did with that.
> Finished problem 26. 

- problemsets-mat223/linearalbegra.tex
Modified the definition of \vec u_\theta ust a tiny bit to make it much more clear, I think. Question 39 in general is a bit weird because the idea of "continuously transforming" a vector will probably be a bit unclear to them. I tried to explain the thinking in 39.2 in some detail, but I'm not sure if I'm at the level you want.
> Finished Problems 39 and 40. 

- problemsets-mat223/linearalbegra.tex
Problem 31 already had some solutions written in, so I just edited them a bit. 
33 and 34 were short so I did them both in one update. 
My solutions to 34 may be a bit too wordy for you, but I hope not.
> Finished Problems 31 through 34.

- problemsets-mat223/linearalbegra.tex
Possibly explained why the component function is linear in too much detail for you.
Also not sure if I'm too wordy in the last part of 42. 
One other thing: In your definition of the Image of a set before Problem 42, are you sure you don't want \vec x and \vec y switched (so it says L(x) = y)?
>  Finished problems 41 and 42.

- problemsets-mat223/linearalbegra.tex
Tying up some loose ends here. 
Problem 13 I had skipped for some reason earlier. Probably because it wants pictures. 
As for Problem 19, I asked a question about the last part earlier, and now I've added a solution for it.
> Finished problems 13 and last part of 19.

- problemsets-mat223/linearalbegra.tex
In problem 30, I don't know if or how much you want explanations for when they're subspaces. All of the explanations will be pretty much of the form "this satisfies the two conditions in the definition above", so it seemed unnecessary. 
Let me know if you'd like to see something more detailed there.
> Finished Problems 29 and 30.

- problemsets-mat223/linearalbegra.tex
Making this one it's own PR, since I suspect you might want me to cut down the solution to the first part a little bit. The solution here has quite a bit of detail about how to find the matrix of a transformation. All the steps needed to understand this are present in previous problems though, which is why I'm not sure if you want it all explained.
> Finished problem 43.

- problemsets-mat223/linearalbegra.tex
Wasn't 100% sure what you are looking for with the last part of 37, about which coordinates better represent the point, so I elaborated a bit.
Also wasn't sure if you wanted a detailed explanation of how to find change of basis matrices. 
Let me know.
> Finished Problems 37 and 38.

- problemsets-mat223/linearalbegra.tex
I think there's going to be a lot to discuss with this one, because I wasn't really sure how you wanted many of these questions answered. 
Problem 46 presents some conceptual things that I don't know how you want me to deal with here. I didn't give any solution for the first part of this problem, because I wasn't sure what you might want there.
Problems 47 and 48 I've answered, but I'm sure you'll want some of them answered in different ways to what I've done. 
I welcome all the criticism/guidance you may have here.
> Problems 46 through 48.

- problemsets-mat223/linearalbegra.tex
Wasn't sure how much more explanation you wanted for the last part of 58. Let me know.
> Problems 56 through 58. 

- problemsets-mat223/linearalbegra.tex
Wasn't sure if you wanted more explanation for 60.2.
> Finished problems 59 and 60.

- problemsets-mat223/linearalbegra.tex
Three things here
- Making sure problems use \xhat, \yhat rather than e_1, e_2 everywhere that I've written solutions for already. Future ones I'll take care of as I see them. 
- \to --> \mapsto for row operations everywhere
- Changing a couple of references to earlier problems into proper \label, \ref links.
> Tying up some loose ends.

- problemsets-mat223/linearalbegra.tex
Tried to use the language of inverse matrices undoing things a lot here.
> Finished Problems 61 and 62.

- problemsets-mat223/linearalbegra.tex
Not sure about the amount of explanation required for the last part given what they've done up to that point about finding matrices of transformations. Tried to keep it relatively brief.
> Finished Problem 63.

- problemsets-mat223/linearalbegra.tex
Being unsure of what they'll know about computing determinants at this point, I was unsure how much explanation you want for these parts. Let me know.
> Finished problems 69 and 70.

- problemsets-mat223/linearalbegra.tex
Problem 71.3: Wasn't sure what sort of explanation you wanted here, since again I'm not sure what they know about determinants by this point. 
Problem 73.3: I might be overlooking something obvious, but isn't it not possible to give the precise dimension of `null(B)` with the information given? All we know is that `\mat{3\\3\\1}` is one vector in that null space, so the dimension is at least 1.
> (Almost) finished problems 71 through 73.

- problemsets-mat223/modules/module14.tex
Git is amazing but GitHubDesktop is not hahaha
> Module 14 Examples finished, Images need to finish

- problemsets-mat223/definitions.tex
> Missing period in Transpose definition

- problemsets-mat223/modules/module6.tex
Please let me know if I can still improve these explanations!
> Module 6 example revisions

- problemsets-mat223/modules/module1.tex
> Module 1 finished

- problemsets-mat223/contributors.tex
- problemsets-mat223/modules/module6.tex
added example in module 6 and added name to contributors
> added example in module 6

- problemsets-mat223/modules/module5.tex
> mathematical typo

- problemsets-mat223/linearalgebra.tex
'representation' -> 'representations'
> fixed typo (singular -> plural)

- problemsets-mat223/modules/module7.tex
While the current solution may be technically correct, it is not consistent with the results obtained by applying the procedure showed in the homework videos, and may lead to unnecessary confusion (it did for me and at least one other student).
> Fixed potential confusion in example

- problemsets-mat223/modules/module7.tex
Same issue as in https://github.com/siefkenj/IBLLinearAlgebra/pull/104
While the current solution may be technically correct, it is not consistent with the results obtained by applying the procedure showed in the homework videos, and may lead to unnecessary confusion (it did for me and at least one other student).
> Another potential confusion in example

- problemsets-mat223/modules/module9.tex
> fixed typo (omission)

- problemsets-mat223/modules/module8.tex
> fixed typo

- problemsets-mat223/modules/module8.tex
> added commas for clarification

- problemsets-mat223/modules/module14.tex
"therefore know" -> "we conclude that"
> Fixed grammar

- problemsets-mat223/modules/module11.tex
`-1` to `-2` in a number of places
> Fixed mathematical typos

- problemsets-mat223/modules/module12.tex
> Fixed typo (word omission)

- problemsets-mat223/modules/module12.tex
> Fixed LaTeX formatting

- problemsets-mat223/modules/module9-exercises.tex
I added solutions to module9-exercises.tex
> added solutions

- problemsets-mat223/contributors.tex
- problemsets-mat223/modules/module1-exercises.tex
- problemsets-mat223/modules/module4.tex
- problemsets-mat223/modules/module7.tex
- Added Xintong (Alucart) Li in the contributor list
- Addressed issue #152 , issue #154 , and issue #156
> Update reg. issue 152,154,156

- book/common/contributors.tex
- book/modules/module12-exercises.tex
- book/modules/module2-exercises.tex
- book/modules/module6-exercises.tex
- book/modules/module7-exercises.tex
- book/modules/module8-exercises.tex
Editted the contributors list.
Added graphs for Module 2 Problem 5, 6, 7, 8.
Fixed typos for:
- Changed "subpace" to "subspace" for Module 6 Problem 1, 2.
- Fixed the rref of A in Module 7 Problem 2 part (a).
- Changed "breifly" to "briefly" for Module 8 Problem 5 part (a), (b).
- Fixed the augmented matrix to identity matrix.
> Added graphs and fixed typos

- book/modules/appendix2.tex
> Added labels for the planes.

- book/modules/appendix1.tex
- 5 examples
- 1 figure
- added a few index entries (not finished)
- fixed some typos/added missing periods
- changed wording of one sentence (line 271)
> Finish Appendix 1 examples

- book/modules/appendix2.tex
> Fix indent in appendix 2 enumerate environment.

- book/modules/appendix2-exercises.tex
- book/modules/appendix2.tex
I finished the question of finding the complete solution of systems, where systems with free variables and a row of zeros have been included. I also included their RREF in the solution for quick preview of each system, but I will write up a proper solution.
I also typed up the question "Setting up a system whose solution will determine ...". Should I write the question by giving different proposals for these questions to address the common errors as mentioned in the chat?
What other types of exercise should I include in this appendix?
> First draft of the Appendix 2 exercises.

- book/common/definitions.tex
- book/linearalgebra.tex
- book/modules/appendix3.tex
- book/modules/module14.tex
- book/modules/module9.tex
This is how the underbraces look in the revised example:
> Add indices and finish missing example in appendix 3, clean up the index

- book/common/preamble.tex
- book/modules/appendix2-exercises.tex
- book/modules/appendix2.tex
- book/modules/appendix3.tex
- book/modules/module1-exercises.tex
- book/modules/module10-exercises.tex
- book/modules/module11-exercises.tex
- book/modules/module12-exercises.tex
- book/modules/module2-exercises.tex
- book/modules/module3-exercises.tex
- book/modules/module4-exercises.tex
- book/modules/module7-exercises.tex
- book/modules/module8-exercises.tex
I added solutions and graphs for some exercises in this commit. I have also changed some appearance of the solutions so that it is easier to read.
> Solutions for modulo exercises

- book/modules/module5-exercises.tex
These are the typos in Module 5 answer. Please check it.
> 2 typo fixed

- book/modules/appendix4.tex
I found a minor calculation error in Appendix 4 while going through the proof of a 2 x 2 determinant which is fixed by this PR.
> Fix a calculation error in proof of 2x2 det.

- book/modules/appendix1-exercises.tex
fixed error in system of equations
> Fix to issue #230

- book/linearalgebra.tex
- book/modules/appendix1.tex
- book/modules/module2.tex
- book/modules/module6.tex
Removed unreferenced labels, and relocated labels found at the beginning of a file to the main .tex file for easy PreTeXt conversion.
> Updated Labels
